### ISSUE TITLE
HTML Entity Codes

### ISSUE THREAD

**Issue by sdhunt** [mshamara/prj-rev-bwfs-dasmoto#2]
https://github.com/mshamara/prj-rev-bwfs-dasmoto/blob/95c09c5057e66ae5dedb5bda996b84495a0a3e35/Dasmoto/index.html#L8

Although browsers will render a lone ampersand (`&`) verbatim, technically this is malformed HTML and should be corrected. The ampersand character has special meaning in HTML; it marks the beginning of an _HTML entity code_. To properly define an ampersand, use the code `&amp;`

See:
* https://developer.mozilla.org/en-US/docs/Glossary/Entity
* https://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

**Comment by mshamara** [comment]
Fixed!
