### ISSUE TITLE
Remember to define `alt` attribute in images

### ISSUE THREAD

**Issue by sdhunt** [mshamara/prj-rev-bwfs-dasmoto#3]
https://github.com/mshamara/prj-rev-bwfs-dasmoto/blob/95c09c5057e66ae5dedb5bda996b84495a0a3e35/Dasmoto/index.html#L10
https://github.com/mshamara/prj-rev-bwfs-dasmoto/blob/95c09c5057e66ae5dedb5bda996b84495a0a3e35/Dasmoto/index.html#L14
https://github.com/mshamara/prj-rev-bwfs-dasmoto/blob/95c09c5057e66ae5dedb5bda996b84495a0a3e35/Dasmoto/index.html#L18

Remember to define an `alt` attribute in the image elements, with text that describes the image. This way, viewers with _accessibility enabled_ will get to hear a verbal description of the image.

**Comment by mshamara** [comment]
Fixed!
