### ISSUE TITLE
HTML Source

### ISSUE THREAD

**Issue by sdhunt** [mshamara/prj-rev-bwfs-dasmoto#4]
Your HTML is not bad, it gets the job done, but it is one dense block of code. 

Adding some whitespace (blank lines) would help improve the readability.

Also, you could use `<div>` elements to group together elements that "go together" as a structure. This will help organize your code, and also provide an opportunity to target those elements with common styling. For example:

```
  <body>
    <h1>Dasmoto's Arts &amp; Crafts</h1>

    <div class="item">
      <h2 id="brush">Brushes</h2>
      <img src="./Resources/hacksaw.jpeg" alt="...">
      <h3>Hacksaw Brushes</h3>
      <p>Made of the highest quality ... </p>
    </div>

    <div class="item">
      <h2 id="frame">Frames</h2>
      <img src="./Resources/frames.jpeg" alt="...">
      <h3>Art Frames (assorted)</h3>
      <p>Assorted frames made of ... </p>
    </div>

    <div class="item">
      <h2 id="paint">Paint</h2>
      <img src="./Resources/finnish.jpeg" alt="...">
      <h3>Clean Finnish Paint</h3>
      <p>Imported paint from ... </p>
    </div>
  </body>
```
with CSS rules, such as:
```
.item h2 {
  font-size: 32px;
  color: white;
}
```

**Comment by mshamara** [comment]
Modified the code for readability, thank you for help!
