### ISSUE TITLE
CSS Source

### ISSUE THREAD

**Issue by sdhunt** [mshamara/prj-rev-bwfs-dasmoto#5]
The CSS is laid out well, following the conventional code styles (lowercase names, indentation inside rule bodies, blank line between rules). Nice work. 

Good to see that there is no duplication, and that you clearly understand the difference between `id` and `class` attributes. 

Note that `h1` and `h2` are `font-weight: bold;` by default, so the rule at line 17 is unnecessary, and can be removed:
https://github.com/mshamara/prj-rev-bwfs-dasmoto/blob/95c09c5057e66ae5dedb5bda996b84495a0a3e35/Dasmoto/Resources/styles.css#L17-L19

**Comment by mshamara** [comment]
Oh, true, didn't think of that. I'll remove it!
