### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by sdhunt** [mshamara/prj-rev-bwfs-dasmoto#6]
Even for such a small project as this, I would recommend keeping stylesheets and images in separate subdirectories... it is a good habit to get into, for when you work on larger projects:

```
    +-- Dasmoto
        +-- index.html
        +-- Resources
            +-- css
            |    +-- style.css
            +-- images
                +-- finnish.jpeg
                +-- frames.jpeg
                 :

**Comment by mshamara** [comment]
I thought to do it so, but then changed my mind. Good to know my first instinct was right!
