### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [mshamara/prj-rev-bwfs-dasmoto#7]
_Grade:_ __Meets Expectations__

Good work creating a web page that meets the project specifications perfectly.  You should feel good about:
* correctly using `id` attributes, vs. `class` attributes
* defining the `.price` class to apply styling to the `<span>` elements for the price text
* using appropriate header elements for the different "levels" of headers (`<h1>`, `<h2>`, `<h2>`)

There are a number of things to pay attention to: 
* Remember to use `&amp;` when defining the ampersand character
* Remember to include a textual description of each image as `alt` text
* Divide up your elements into groups with `<div>` elements, when appropriate
* Use whitespace (and possibly comments) to help visually break up the code

Some further reading: 
* https://learn.shayhowe.com/html-css/writing-your-best-code/

You've made a great start on your journey to writing awesome web pages.

Keep up the good work!

**Comment by mshamara** [comment]
Thank you, this was fun task and I'm looking forward to getting to next ones!
